### ISSUE TITLE
[TA] Comments for Team1's presentation

### ISSUE THREAD

**Issue by oxsignal** [KAIST-IS521/2018s-presentation-team1#11]
Hi all, This is TA of your team.

I am writing this issue for informing the comments from TA and Prof. Cha

First of all, I really apologize that being late at the  class.

Even though our team has not won the best presentation, you all have done good work.

The score on the presentation will be notified soon.

## The presentation time taken by each member
```
1. 2분 58초
2. 2분 51초
3. 2분 19초
4. 2분 45초
Total: 11분 40초 (Including  concluding remarks)

Comments : Excellent :)
```

## Overall comments
```
"I wanted to see more about yourself, but not about your vimrc conf.
 The main reason why I asked to present your environment settings is to help you sell about yourself. 
However, your presentation is mainly focused on details about your configuration, which is not
necessarily interesting to many people. I liked the overall flow though, and also liked the team name :)"

"Only explain Config(.*rc) file, not themselves."

"Good to see the unified form of slides"

"You need to make it more attractive with visual aids"

"Very good to follow grading criteria"

""WORKING ENVIRONMENT"" slides does not show anything, I think they should be removed."

"Presentation was focused on the working environment, we want to know more information about yourself."

"It was good to strictly follow the guidlines and grading criteria"

"it was not easy to follow the ""working environment"". 

"Well distributed time window each people use."

"The only thing breaks unity of design is one of slides from Mincheol without title.

"Presentation was good"

"But could have made the presentation more appealing and intruging 
(explaining configuration file line by line may not grab the audience's attention)"
```

## Individual comments

```
- Dauren: You'd better be more passionate. Please speak up!

- Seong ho: You could have talked more about your research area (Post-quantum crypto).

- Min cheol: you could have shown more about yourself.

- Jiwon: Be more confident when you give a presentation. You'd better speak up.

- I cannot see any significant difference between the members

- Insufficient PR on the presentation
```
----

Please be informed that the professor does not want that his students only focus on their grades, but develop their skills and abilities through the class.

The presentation on this Monday is not bad at all, so please be not disappointed with your score.

 Finally, I leave some helpful tips through our class.
 1. Use github as many as possible. 
 Your activity on the github is always being watched and important criteria in the class.

 2. Be interactive with your team. If you have any question on the class or activity, first google it and ask
it to your team if you cannot get the answer. Some of activities on the class need effective and efficient teamwork. Please do not hesitate interacting with your team. 

You can close this issue when every member gets this.

**Comment by oxsignal** [comment]
Does not have neat and tidy form since I wrote this issue on the phone due to my personel situation, will update soon.  Thanks

**Comment by hansh17** [comment]
Thanks for your comment. I'll keep in mind your advise.
