### ISSUE TITLE
Ask TA  about team leader

### ISSUE THREAD

**Issue by hansh17** [KAIST-IS521/2018s-presentation-team1#17]
Can I give my role (team leader) to other person?

If we changed our team leader, what could be happened?

**Comment by sangkilc** [comment]
I am okay with that. Who's gonna take it?

**Comment by hansh17** [comment]
Jiwon choi will be a team leader. 
I  talked with her enough. Other team members agreed that she would be a team leader.
Is there any process to change leader?

**Comment by sangkilc** [comment]
Fix the README.md in your team presentation repo.
