### ISSUE TITLE
[TA] Tips for using your milestone and issues

### ISSUE THREAD

**Issue by oxsignal** [KAIST-IS521/2018s-presentation-team1#6]
1. Using Labels is recommended to know what the issues related to.

2. Sign your commit first via GPG when you push your commit on a git repository. 

Not mandatory, but recommended

**Comment by hansh17** [comment]
Thank you for comments. But I'm not sure about your 2nd recommendation. What stands for GPG?

**Comment by oxsignal** [comment]
You will learn it soon. If you wonder please google it. As I said, it is not  mandatory.
